### ISSUE TITLE
Edilizia: allegati strutturati

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#10]
E' auspicabile che gli allegati che sono stati definiti in modo strutturato nella modulistica edilizia (es. Relazione Tecnica di Asseverazione e Soggetti Coinvolti) siano tradotti in porzioni dell'XSD

**Comment by vintra73** [comment]
Le confermo che obiettivo del GdL è la formalizzazione in XSD di tutti i contenuti approvati in conferenza, quindi di specie anche gli allegati definiti quali ad esempio: SOGGETTI COINVOLTI, DICHIARAZIONI DEL PROGETTISTA, RELAZIONE TECNICA DI ASSEVERAZIONE, ...
