### ISSUE TITLE
SUAP: Imprese pulizie - requisiti professionali dichiarante o altro responsabile tecnico

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#100]
Si segnala che nel modulo 
**SUAP_modulo_imprese_pulizie.xsd**
viene richiesto obbligatoriamente di indicare i dati requisiti professionali del dichiarante, o i dati del responsabile tecnico preposto:
_<xs:element name="dichiarazioni" type="imppulizie:DichiarazioniType"/>_
ma tali informazioni dovrebbero essere presenti solo nel caso di esercizio di attività di disinfestazione, derattizzazione, sanificazione (cfr. pag 3 del modulo cartaceo).

**Comment by giacomo83** [comment]
Grazie per la segnalazione

**Comment by giacomo83** [comment]
Fixed by commit e269b1a54c38dd286cec24c5ec3ead8114836ae4
