### ISSUE TITLE
SUAP: informazioni sul procuratore

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#101]
Si segnala che nel modulo:
 **SUAP_common_components.xsd**
l'elemento:
 _ProcuratoreType_
prevede la scelta tra _ProcuraDelega_ e _AgenziaImprese_, ma poi prevede sempre obbligatorio il campo _denominazioneAgenziaImprese_, legato però solo ad _AgenziaImprese_.

**Comment by giacomo83** [comment]
Fixed by commit 4dd78e14d58814b9691e8e80e69bd55095a8acb0
