### ISSUE TITLE
SUE: legale rappresentante ditta esecutrice dei lavori

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#102]
Si segnala che nel modello cartaceo **D-SOGGETTI COINVOLTI** per il Legale Rappresentante dell'Impresa Esecutrice (sezione 3) non sono previsti i dati sulla residenza.
L'elemento _legaleRappresentante_ presente in **SUE_common_components.xsd** fa invece riferimento ad _aggregate:PersonaAnagraficaType_ che prevede obbligatoriamente i dati sulla residenza.

**Comment by giacomo83** [comment]
Fixed by commit 43c05822cbefe5d0ccd6d18e3aa4a45383095d2b
