### ISSUE TITLE
SUE: Agibilità - Info Presentazione Inizio Lavori

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#103]
Si segnala che nel modulo 
**SUE_modulo_segnalazione_certificata_agibilita.xsd**
l'elemento 
_PresentazioneInizioLavoriType_
contiene una prima choice per la presentazione delle agibilità relative a SCIA e SCIA Unica ed una seconda choice per ulteriori allegati relativi alle sezioni B e C.
Tale elemento, contenente:
_allegaAttestazioneProfessionista
allegaComunicazioni_
NON dovrebbe prevede l'esclusività tra questi due campi, pertanto la seconda choice dovrebbe diventare una sequence di 2 elementi non obbligatori.

**Comment by giacomo83** [comment]
fixed by commit 588bbd7e9a2b6068cac13a028dbcc94fe742ef9f
