### ISSUE TITLE
SUE: Relazione Tecnica Asseverazione - Scarichi idrici

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#104]
Si segnala che nel modulo:
**SUE_common_components.xsd**
l'elemento _ScarichiIdriciType_
dovrebbe contenere elementi tra loro alternativi.

**Comment by giacomo83** [comment]
Grazie per la segnazione

**Comment by giacomo83** [comment]
fixed by commit d9182d1d600faaed071feceffcf901b3b3033d87
