### ISSUE TITLE
SUE: Regolarità Urbanistica

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#105]
Si segnala che nel modulo:
**SUE_common_components.xsd**
l'elemento _pienamenteConforme_ di _RegolaritaUrbanisticaOptionGroup_
NON dovrebbe contenere il campo obbligatorio _dataRealizzazioneOpere_ ereditato da _InDifformitaType_

**Comment by ilariabrunoinfocamere** [comment]
Sempre per la Regolarità Urbanistica nel modulo:
**SUE_modulo_scia_alternativa.xsd**
manca l'opzione aggiuntiva (e NON alternativa alle altre 3 presenti in _RegolaritaUrbanisticaOptionGroup_):
f.4	•	per lo stesso immobile sono in corso interventi / sono state presentate pratiche per interventi di _______________________________________	con pratica 	n.   _________	del   |__|__|__|__|__|__|__|__|

**Comment by ilariabrunoinfocamere** [comment]
Per il modulo:
**SUE_modulo_permesso_costruire.xsd**
l'opzione _praticheStessoImmobile_ (e.2.4 nella modulistica cartacea)
NON dovrebbe essere alternativa alle altre 3 voci, ma in aggiunta e facoltativa.

**Comment by giacomo83** [comment]
Grazie per le segnazioni!

**Comment by giacomo83** [comment]
fixed by commits b8687232a114813d8d08b42eead462adbbd70dfd and  b8687232a114813d8d08b42eead462adbbd70dfd
