### ISSUE TITLE
SUE: Scheda Ditta e Procuratore in SCIA, PdC, SCIA alternativa al PdC

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#108]
Si segnala che nei moduli:
**SUE_modulo_scia.xsd
SUE_modulo_permesso_costruire.xsd
SUE_modulo_scia_alternativa.xsd**
gli elementi:
_schedaDitta
schedaDelegato_
NON devono essere obbligatori.

**Comment by giacomo83** [comment]
Grazie per la segnalazione!

**Comment by giacomo83** [comment]
fixed by commit f66514e446a41085ac4d6ebf46ce6e01465a5377
