### ISSUE TITLE
SUE: Permesso di Costruire - Qualificazione intervento

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#109]
Si segnala che nel modulo:
**SUE_modulo_permesso_costruire.xsd**
l'elemento _QualificazioneInterventoType_
(ad esclusione di _procedimentoOrdinario_ che è a parte) dovrebbe contenere scelte NON mutuamente esclusive.

**Comment by giacomo83** [comment]
Grazie per la segnalazione!

**Comment by giacomo83** [comment]
Si richiede se tale osservazione sull'elemento _QualificazioneInterventoType_ è da ritenersi valida anche in:
- **SUE_modulo_scia.xsd**
- **SUE_modulo_cila.xsd**

**Comment by ilariabrunoinfocamere** [comment]
Per SCIA e CILA va bene la mutua esclusività delle opzioni, grazie!

**Comment by ilariabrunoinfocamere** [comment]
Abbiamo rivisto il modulo del Permesso di Costruire, e concordiamo che le scelte debbano essere mutuamente esclusive.
Scusate per l'errata segnalazione.

**Comment by giacomo83** [comment]
OK grazie!
