### ISSUE TITLE
Edilizia: SCIA/SCIA unica/SCIA condizionata

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#11]
Alcune informazioni, come ad es. il tipo di SCIA, sono desumibili dai procedimenti selezionati.
Potrebbe pertanto non essere necessario riportarli come campi compilabili dall'utente.

**Comment by vintra73** [comment]
La nostra intenzione è quella di operare in maniera similare a quanto fatto per i moduli SUAP eliminando la ridondanza delle informazioni dai moduli. 

A tale proposito ricordo che per i moduli SUAP, ad esempio, nel formato cartaceo vi era la necessità, da parte del soggetto proponente l'istanza, di indicare il regime amministrativo selezionato e nel contempo indicare gli allegati relativamente al regime amministrativo selezionato, mentre negli XSD definiti abbiamo condiviso con il GdL che suddividendo gli Allegati in gruppi relativi al regime amministrativo non vi è più la necessità di registrare il regime amministrativo utilizzato perché deducibile dagli allegati indicati.
