### ISSUE TITLE
Apparente incongruenza negli xsd SUAP presenti in:  https://github.com/italia/moduli-pa/tree/master/Moduli_PA/SUAP 

### ISSUE THREAD

**Issue by gisadev** [italia/moduli-pa#110]
nei file:
- SUAP_modulo_somministrazione_scuole_ospedali_ecc.xsd
-  SUAP_modulo_somministrazione_aree_servizio.xsd

Partendo dal nodo root, manca  la sezione 
 tabellaAllegati
  -- allegatiSCIAUnica
    --- allegatoNotificaSanitaria
      ---- notificaSanitaria

nonostante la chiara appartenenza all'ambito alimentare.

**Comment by giacomo83** [comment]
La gestione degli allegati è stata oggetto di refactoring cosi come visibile sul branch  https://github.com/italia/moduli-pa/tree/dev-v1.1.1

A breve effetueremo il merge sul ramo master.
