### ISSUE TITLE
SUAP: modulo vicinato

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#111]
Si segnala che nel modulo:
**SUAP_modulo_vicinato.xsd**
nell'elemento 
_AllegatiSCIAUnicaType_
è presente due volte:
_allegatoNotificaSanitaria_

**Comment by giacomo83** [comment]
Grazie per la segnalazione!

**Comment by giacomo83** [comment]
Fixed by commit e39263d945430cb457b40703a7b1c4beed18b923
