### ISSUE TITLE
Personalizzazione xsd schema per specifico ambito regionale

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#113]
Buongiorno,
nel tavolo modulistica è stato previsto che alcune sezioni dei moduli approvati possano essere personalizzate dalle singole regioni sulla base della propria legislazione.
Queste personalizzazioni si traducono in personalizzazioni degli xsd dello specifico modulo andando ad estendere gli specifici elementi informativi? Come si può garantire che l'xml prodotto sulla base di uno schema personalizzato regionale possa essere validato anche dal corrispondente shema nazionale nell'ipotesi che quell'xml venga trasmesso da un ente di livello regionale ad un ente di livello nazionale coinvolto sul procedimento?
In attesa di un riscontro
Cordiali Sauti
Fabio Bennati (Regione Toscana)

**Comment by giacomo83** [comment]
Le esigenze di personalizzazione degli XSD nazionali da parte delle regioni derivano dalla presenza di sezioni della modulistica che possono variare sulla base della diversa legislazione regionale.

Nell'ambito delle proprie attività il GdL XML ha indirizzato tale problematica adottando nella fase di definizione degli XSD  il seguente pattern:
- per ogni sezione variabile su base regionale nella modulistica il corrispondente data type nell'XSD è stato definito astratto.
- per ogni data type definito astratto è stata definita un implementazione nazionale corrispondente a quella definita sul modulo.

Le regioni sulla base delle proprie esigenze procedono alla realizzazione delle proprie specializzazioni, attraverso la definizione dei propri schemi XSD,  estendendo se necessario i tipi definiti astratti in ambito nazionale con la definizione di un proprio relativo.

La validazione è da eseguire rispetto agli schemi regionali che comprendono le specializzazioni.
