### ISSUE TITLE
SUE: Agibilità - Attestazione tecnica

### ISSUE THREAD

**Issue by elianagrenziinfocamere** [italia/moduli-pa#115]
Si segnala che nel modulo
**SUE_modulo_segnalazione_certificata_agibilita.xsd**

nella sezione **Prevenzione Incendi, ascensori/montacarichi**
l'elemento
_MontacarichiBaseType_
contiene una choice per la presentazione del documento di "Attestazione Tecnica della S.C.I.A. per Agibilità - Art. 24 del D.P.R. 380/2001"
Tale elemento, contenente:
_comunicazioneValidaPerMatricola
attoComunicazione_
NON dovrebbe prevede l'esclusività tra questi due campi, pertanto la choice riportata dovrebbe diventare una sequence di 2 elementi non obbligatori.

nella sezione **Barriere architettoniche, Catasto, Toponomastica**
l'elemento
_ToponomasticaType_
contiene:
_comportaVariazioneCivici_
dove è prevista una choice per i campi
_allegaRichiestaNumerazione
protocolloVariazioneNumerazione_
che dovrebbe diventare una sequence di 2 elementi

nella sezione **Sicurezza degli impianti**
l'elemento
_SicurezzaImpiantiType_
contiene:
_impiantiConCertificazione_
Tale elemento, contenente:
_linee vita
altro_
dovrebbe prevedere l'obbligatorietà per questi due elementi.

**Comment by giacomo83** [comment]
Fix by #119
