### ISSUE TITLE
SUE_common_components - ProfessionistaAnagraficaDirettoreType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#116]
Il tipo contiene una scelta:
                <xs:choice minOccurs="0">
                    <xs:element name="direttoreLavori" type="basic:EmptyType" />
                    <xs:element name="professionistaAbilitato" type="basic:EmptyType" />
                </xs:choice>
L'opzione "direttore Lavori" è ritrovabile nel documento rilasciato dei soggetti coinvolti.
Non riesco a capire da dove tragga la sua presenza l'opzione "professionista Abilitato".

**Comment by giacomo83** [comment]
Abbiamo riscontrato la segnalazione, procedermo al relativo fix nel prossimo ciclo di refactoring.

**Comment by giacomo83** [comment]
Fix by #119
