### ISSUE TITLE
SUE_common_components - ProfessionistaAnagraficaType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#117]
Il tipo che viene utilizzato per tutti i professionisti non contiene una struttura informativa atta a contentere i dati della residenza  del soggetto come presente nel modulo rilasciato dalla conferenza.
Può ritenersi un refuso o visto che per i professionisti viene riportata la sede dello studio professionale risulta superflua la residenza personale?

**Comment by giacomo83** [comment]
Abbiamo riscontrato la segnalazione e quanto indicato è da considerarsi un refuso, procedermo al relativo fix nel prossimo ciclo di refactoring aggiungendo le informazioni per l'indirizzo di residenza per il type in oggetti.

**Comment by giacomo83** [comment]
Fix by #119
