### ISSUE TITLE
Edilizia: sezioni simili tra i modelli

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#12]
Come già fatto per i modelli relativi al SUAP, è auspicabile che si arrivi a definire il più possibile blocchi di informazioni comuni condivisi tra più modelli.
Al momento la modulistica edilizia presenta blocchi diversi, se pur molto simili, che verranno trattati come oggetti diversi, ma che in futuro, con una revisione congiunta con il tavolo governato da Funzione Pubblica che ne definisce i contenuti, potrebbero essere rivisti in ottica di razionalizzazione.

**Comment by vintra73** [comment]
In merito confermo che il lavoro che realizzeremo ha come obiettivo è quello di astrarre i tipi al di la della loro presenza all'interno di uno specifico modulo, continuando a lavorare sul modello a tre livelli di astrazioni già adottati per il SUAP:
- AgID Vocabularies, type/element generali per la tipizzazione dei dati delle pubbliche amministrazioni
- MODULI_common_components, type/element utilizzati per tutti i moduli indipendentemente dagli ambiti
- <AMBITO>_common_components, type/element utilizzati per tutti i moduli di uno specifico ambito nello specifico SUAP e SUE

Relativamente alla richiesta di **rivisitare i contenuti in un'ottica di razionalizzazione**, allo stato il nostro mandato non ci permette di impattare sui contenuti approvati in Conferenza Unificata
