### ISSUE TITLE
SUE: Agibilità - AsseveraType

### ISSUE THREAD

**Issue by elianagrenziinfocamere** [italia/moduli-pa#120]
Si segnala che nel modulo
SUE_modulo_segnalazione_certificata_agibilita.xsd
l'elemento  AsseveraType  
contiene una choice dove l'elemento **agibilitaSingoliImmbobili** ha una nomenclatura non corretta.

**Comment by giacomo83** [comment]
Grazie per la segnalazione

**Comment by giacomo83** [comment]
Fix by ee22c8061e15a6f921a842d9aaa0adb0ade70fab
