### ISSUE TITLE
SUAP: Esercizio di Vicinato - carattere esercizio

### ISSUE THREAD

**Issue by elianagrenziinfocamere** [italia/moduli-pa#121]
SUAP: Esercizio di Vicinato

Si segnala che nel modulo **SUAP_modulo_vicinato.xsd**

l'elemento CarattereEsercizioType
contiene una scelta multipla per il carattere dell'esercizio
-   CaratterePermanente
-   CarattereStagionale
-   CarattereTemporaneo 

si propone di prevedere una scelta esclusiva per tali campi oppure di impostare anche per CarattereStagonale e CarattereTemporaneo il minOccurs="0" maxOccurs="1".

**Comment by giacomo83** [comment]
Fix by 076a93f682791449471aa0ff1c057de8887f19e1
