### ISSUE TITLE
SUE: CILA - Dichiarazioni progettista

### ISSUE THREAD

**Issue by GisMasterTD** [italia/moduli-pa#122]
Si chiedono delucidazioni sulla compilazione della sezione "dichiarazioniProgettista" ed in particolare dei nodi "altreComunicazioni" e "attiDiAssenso".
Data la struttura del modello di asseverazione che tipo di dato occorre inserire nei nodi "ComunicazioniSegnalazioniType.comunicazioni" e "ComunicazioniSegnalazioniType.autoritaCompetente"?
Stesso problema su "AttiAssensoType.tipoAtto" e "AttiAssensoType.autoritaCompetente".
Ad esempio il capitolo "Tutela dall’inquinamento acustico" come andrebbe valorizzato nell'xml?
Ed il capitolo "Prevenzione incendi"?

**Comment by giacomo83** [comment]
In merito alla valorizzazione di:
- ComunicazioniSegnalazioniType.comunicazioni
- ComunicazioniSegnalazioniType.autoritaCompetente
- AttiAssensoType.tipoAtto
- AttiAssensoType.autoritaCompetente
Essendo le stesse informazioni in testo libero sul modulo, nella struttura dati XML definita mediante lo schema XSD relativo queste sono memorizzate come stringhe.

Relativamente ai citati  "Tutela dall’inquinamento acustico" e "Prevenzione incendi" non si trova riscondo nel modulo segnalato (CILA: COMUNICAZIONE INIZIO LAVORI ASSEVERATA )
