### ISSUE TITLE
SUE_common_components - LocalizzazioneInterventoType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#123]
Il complex Type LocalizzazioneInterventoType è composto da: 
- un elemento ubicazioneImmobile che consente di rappresentare un unico indirizzo, esteso delle informazioni relative a scala, piano, interno;
- un elemento datiCatastali che consente di rappresentare un unica coordinata catastale (terreni o fabbricati) specifica di un comune catastale;
- un elemento destinazioneDUso che consente di gestire un unica destinazione d'uso

Se l'obiettivo del tipo è consentire la localizzazione dell'intervento edilizio in termini di indirizzi, elementi catastali, destinazione d'uso degli elementi catastali coinvolti appare insufficiente la suddetta struttura.

Se i casi di localizzazione dell'intervento che si devono poter rappresentare sono:
1) un solo indirizzo, una sola coordinata catastale ed una sola destinazione d'uso
2) un solo indirizzo collegato a più coordinate catastali, tutte collegate ad una sola destinazione d'uso
3) un solo indirizzo collegato a più coordinate catastali, ciascuna collegata ad una destinazione d'uso, ma che complessivamente risultano collegate a più destinazioni d'uso
4) più indirizzi collegati ciascuno a una o più coordinate catastali, ciascuna collegata ad una destinazione d'uso, ma che complessivamente risultano collegate a più destinazioni d'uso
la struttura che si sembra più adatta alla rappresentazione potrebbe essere la seguente:

    <xs:complexType name="LocalizzazioneInterventoType">
        <xs:sequence>
            <xs:element name="immobile" type="suecommon:LocalizzazioneImmobileType" maxOccurs="unbounded"/>
       </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LocalizzazioneImmobileType">
        <xs:sequence>
            <xs:element name="ubicazioneImmobile" type="suecommon:UbicazioneImmobileType" />
            <xs:element name="datiCatastali" type="moduli:DatiCatastaliType" maxOccurs="unbounded"/>
            <xs:element name="destinazioneDUso" type="xs:string" />
            <xs:element name="coordinate" type="suecommon:CoordinateBaseType" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

Questo anche considerando che la stessa struttura viene utilizzata per la localizzazione degli intereventi in più moduli edilizi (CILA, CIL, PDC, SCIA, SCIA alternativa)

**Comment by giacomo83** [comment]
Riteniamo la segnalazione di interesse, si è proceduto a fare una variazione dell'implementazione proposta in quanto la stessa non sembra indirizzare perfettamente la casistica 3, e la casistica due 2 è generalizzabile dalla casistica 3 assumendo la destinazione d'uso con un informazione accoppiata al singolo oggetto catastale.
Vedi commit 034afb78fc39526fb7bb85fbade6a2b7caed8d1a
