### ISSUE TITLE
Scheda Anagrafica

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#14]
Alcune sezioni dei tracciati (come quelle relative ad es. alla scheda anagrafica, all'indirizzo e ai dati catastali dell'impianto), sono in realtà già contenute nel modello di riepilogo della pratica SUAP (SUAP.XML) definito dal tavolo nazionale per le regole tecniche relative al DPR160/2010.
Funzione Pubblica, nel definire la modulistica standardizzata, ha trattato la scheda anagrafica come una sezione comune a tutti i modelli, con l'evidente intento di escluderla dai moduli cartacei, ma anche dai relativi tracciati.
In virtù di questo, per evitare duplicazione di dati nei vari MDA.XML che costituiscono la pratica, ci chiediamo se abbia senso mantenere la scheda anagrafica anche all'interno dei modelli, oltre che nel riepilogo SUAP.XML.

**Comment by vintra73** [comment]
Buongiorno,
in merito le segnalo che dalla lettura delle istruzione i moduli sono da intendersi come unione della scheda anagrafica, comune a tutti, e gli specifici moduli.

Nella definizione da noi realizzata abbiamo generalizzato la scheda anagrafica con il type SchedaAnagraficaSUAPType presente nel SUAP_common_components-1.0.0.xsd.

Il mandato del GdL è quello di formalizzare quanto approvato in Conferenza Unificata, non abbiamo in nessun modo inteso modificare i contenuti in esso previsti. Relativamente alla segnalazione che alcuni dei contenuti sono già presenti nel modello riepilogativo ella pratica SUAP (SUAP.XML) definito dal tavolo nazionale per le regole tecniche relative al DPR160/2010, le chiederei di verificare la copertura dell'insieme dei dati indicati in Conferenza Unificata; se necessario abbiamo ancora il tempo di allineare il type definiti.

Credo che sia necessario affrontare nell'incontro di oggi la riflessione.
