### ISSUE TITLE
Criteri adozione versioni schemi XSD

### ISSUE THREAD

**Issue by caramella** [italia/moduli-pa#140]
In merito ai criteri di adozione degli schemi XSD, si chiede se gli enti territoriali debbono adottare esclusivamente le versioni citate nelle conferenze unificate oppure le ultime rilasciate su Github.
Un caso specifico, ad oggi,  è quello relativo all'ultima Conferenza Unificata del 17 Aprile 2019, che negli allegati tecnici fa riferimento alla versione 1.2.0. Il 1 luglio, su github, il GdL ha rilasciato una versione successiva, la 1.2.1. In questo, caso quale delle versioni va adottata?

**Comment by giacomo83** [comment]
Lo schema di versioning adottato, conformemente al “Semantic Versioning 2.0.0”  prevede un identificativo numerico a tre livelli <MAJOR>.<MINOR>.<PATCH> (ad esempio 1.0.1). 
Nello specifico della attività del GdL XML Schema si sono declinati i tre livelli nel seguente modo:
- MAJOR: incrementato per ogni aggiornamento normativo recepito che abbia impatto sui moduli della Pubblica amministrazione;
- MINOR: incrementato ad ogni aggiunta di nuovi moduli al set di quelli esistenti;
- PATCH: incrementato alla conclusione delle azioni di fix bug e refactoring.

Il numero di versione corrente è riferito all’intero del corpo degli XML Schema realizzati, per facilitare il recupero a blocchi degli schemi anche con lo strumento di releasing offerto da GitHub.

In numero di versione è comunque mantenuto in ogni file XML Schema nell’attributo “version” del tag “schema” del file stesso.

Gli schemi allegati in sede di Conferenza Unificata sono correlati a cambi di versione su i livelli MAJOR.MINOR il livello PATCH viene manutentuto dal GdL XML Schema coordinato da AgID e pubblicato sulla piattaforma GitHub.

Sulla base dello schema di versioning adottato, la sua richiesta trova risposta nel seguente modo:
La versione di riferirmento da utilizzare è quella relativa sempre all'ultima release pubblicata su GitHub,

Cogliamo l'occasione per segnalare che in prossimità della approvazioni della modulistica in Conferenza Unificata, la release è anticipata su GitHub con all'interno la seguente indicazione:
**_(In Attesa di approvazione in CU)_** 
A valle dell'approvazione l'indicazione è sostituita con il riferimento dell'accordo.
