### ISSUE TITLE
Modulo SUAP_modulo_acconciatori_estetisti.xsd: superficeComplessivaType

### ISSUE THREAD

**Issue by elianagrenziinfocamere** [italia/moduli-pa#144]
Si segnala che nel modulo **SUAP_modulo_acconciatori_estetisti.xsd**
viene richiamato superficeComplessivaBaseType anzichè superficeComplessivaType:

<xs:element name="superficeComplessiva" type="acconcestet:**superficeComplessivaBaseType**" />
<xs:complexType name="superficeComplessivaBaseType" abstract="true" />
    <xs:complexType name="superficeComplessivaType">
        <xs:complexContent>
            <xs:extension base="acconcestet:superficeComplessivaBaseType">
                <xs:sequence>
                    <xs:element name="mq" type="xs:decimal"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

Stesso problema su:
superficeComplessiva
superficeAdibitaAttivita
inCentroCommerciale
attivitaEsercitata

**Comment by jackom83** [comment]
Grazie per la segnalazione, procediamo con l'analisi della stessa con il GdL.

**Comment by jackom83** [comment]
L'implementazione realizzata con l'utilizzo dei type abstract è corretta in quanto tale pattern è stato adottato per la gestione delle sezioni della modulistica personalizzabili in virtù di normative regionali e contrassegnate sulla modulistica stessa con il simbolo *
