### ISSUE TITLE
Proposta Regione Lombardia: aggiungere booleano per segnalare presenza (o meno) di una sezione opzionale

### ISSUE THREAD

**Issue by fmadonia** [italia/moduli-pa#2]
La proposta di RL è la seguente: aggiungere un campo booleano per anticipare la presenza (o meno) di una particolare sezione opzionale (vedi sezione Procuratore). Non è richiesto di aggiungere il campo booleano a tappeto prima di ogni blocco opzionale, ma di inserirlo in modo puntuale su alcune sezioni di importanza rilevante.
Motivazioni: facilitare i controlli logici e facilitare lo sviluppo della modulistica.
Esempio: di seguito un esempio per i dati del Procuratore.

As Is:
    <xs:complexType name="SchedaAnagraficaSUAPType">
        <xs:sequence>
            <xs:element name="datiDichiarante" type="suapcommon:DichiaranteType"/>
            <xs:element name="datiImpresa" type="suapcommon:ImpresaType"/>
            <xs:element name="datiProcuratore" type="suapcommon:ProcuratoreType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

To Be:
    <xs:complexType name="SchedaAnagraficaSUAPType">
        <xs:sequence>
            <xs:element name="datiDichiarante" type="suapcommon:DichiaranteType"/>
            <xs:element name="datiImpresa" type="suapcommon:ImpresaType"/>
            <xs:element name="datiProcuratoreCheck" type="xs:boolean" default="false"/>
            <xs:element name="datiProcuratore" type="suapcommon:ProcuratoreType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

**Comment by vintra73** [comment]
In merito alla proposta formulata segnaliamo che nella fase implementativa degli XSD è stato considerata anche l'ipotesi formulata da RL. 

Si era deciso di non inserire un campo booleano per anticipare la presenza di una particolare sezione in quanto:

- Tale informazione risulta ridondante, il che aumenta la possibilità di incoerenza complessiva del XML prodotto, ad esempio si possono presentare il caso in cui datiProcuratoreCheck=true e datiProcuratore=NULL.

- La presenza o meno di una struttura complessa permettere di realizzare l'equivalente controllo attraverso, ad esempio, l'opportuna espressione XPath ( nell'esempio [..]/SchedaAnagraficaSUAPType/datiProcuratore ) che può restituire il nodo se presente oppure un NOMATCH in caso di assenza.

Sulla scorta delle valutazioni riportate in precedenza non si ritrova l'esigenza di aggiungere un campo booleano per "facilitare i controlli logici". 

Non essendo chiaro in che modo la presenza del campo booleano possa "facilitare lo sviluppo della modulistica", si evidenzia la necessità di approfondire il punto con i colleghi di RL.
