### ISSUE TITLE
Considerazioni Regione Friuli Venezia Giulia

### ISSUE THREAD

**Issue by massimodecolle** [italia/moduli-pa#3]
Buongiorno,  dopo aver analizzato la prima release degli xml schema caricati volevamo fare le seguenti considerazioni:

- In tutti gli schemi specifici dei moduli denominati SUAP_modulo_xxxxx sono definiti una serie di “complex type” ma non sono definiti “element” globali che li utilizzino. Questo di per se non rende possibile creare istanze xml a partire dagli xsd schema forniti. Quello che vorremo capire è se gli “element” verranno aggiunti in seguito o se questa attività è demandata alle regioni che importando gli schemi già definiti possono crearne di propri, con propri name space. Gli element creati apparterrebbero ai namespace degli schema regionali.

- Prendendo in considerazione i complex type definiti di tipo “abstract” che consentono quindi la specializzazione in caso di necessità da parte delle regioni, qual è la politica che si intende adottare?Mi spiego meglio. Eventuali estensioni dei tipi astratti dovranno essere forniti ad AgID per essere inseriti negli stessi schema pubblicati o potranno essere estesi in  schema xsd delle singole regioni ridefinendo anche in questo caso il namespace?

- In generale si è fatto un uso abbastanza esteso di enumeration, restriction sulla base di regular expression per definire compiutamente il modello. Fino a che il modello non si sarà stabilizzato potrebbe verificarsi l’eventualità di qualche correzione. Quale  sarà la politica con la quale si intende gestire il versionamento degli schemi ? 
Grazie

**Comment by vintra73** [comment]
A seguire le risposte hai dubbi sollevati:

- relativamente alla necessità di prevedere dei root element per i file SUAP_modulo_xxxxx è intenzione aggiungerli prevedendo la definizione di un element tipizzato con il tipo che definisce il modulo nel suo complesso, ad esempio per il file SUAP_modulo_somministrazione_temporanea-1.0.0.xsd definire un elmente tipizzato a ModuloSomministrazioneTemporaneaType, nello specifico:

<xs:element name="ModuloSomministrazioneTemporanea" type="ModuloSomministrazioneTemporaneaType"/>

- l'utilizzo degli abstract deriva dalla volontà di assicurare alle Regione di dare seguito alla definizione di schemi personalizzati in conformità alla normativa di merito, l'AgID assicura la definizione di un tipo abstract che definisce la struttura di base e nel contempo un'istanza dello stesso abstrac implementate i contenuti previsti nei moduli accettati in Confernza Unifica, resta a carico delle Regione, se necessario, definire gli schemi che implementando il tipo abstract fornito lo estendo per assicurare le esigenze locali; si precisa che le Regione operano in piena autonomia per dare seguito alla conformità della normativa locale ed è incoraggiato la diffusione di quanto prodotto al fine di incrementare la condivisione delle esperienze e pratiche a tutti i soggetti interessati

- si è consapevoli della possibilità che l'utilizzo di tipi ristretti, come gli enumeration, possano determinare variazione degli schemi dati, ma nonostante tale consapevolezza siamo convinti che per aumentare l'interoperabilità dei sistemi non sia possibile rilassare i vincoli sui valori ammessi accettando di gestire le conseguenze all'aggiornamento degli schemi; nella definizione del modalità di change managment degli schemi saranno considerati i tempi necessari all'aggiornamento dei sistemi al mutare degli schemi, in linea di principio sarà necessario assicurare la retro compatibilità delle nuove formulazioni degli schemi con le precedenti anche attraverso la disponibilità di più versioni degli schemi per periodi transitori per permettere l'assorbimento delle variazioni alle implementazioni realizzate
