### ISSUE TITLE
Edilizia: trattazione scelte nidificate

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#31]
In merito alla questione sollevata nella call del 16/10 su come trattare alcuni campi (es. modulo B1 - sezione c - campi c.2/c.2.1, c.3/c.3.1), segnaliamo che impresainungiorno è andata nella direzione di semplificare la compilazione della sezione, utilizzando un'unica selezione in cui sono comprese sia la voce padre che l'unica voce figlia.
A titolo di esempio si riporta proprio il caso segnalato nella call:
MODULO:
c.2	•	intervento in corso di esecuzione, con pagamento di sanzione (d.P.R. n. 380/2001, articolo 37, comma 5), e pertanto si allega 
c.2.1	•    	la ricevuta di versamento di € 516,00
INTERFACCIA DI COMPILAZIONE:
intervento in corso di esecuzione, ai sensi dell’articolo 37, comma 5 del d.P.R. n. 380/2001, con pagamento di sanzione, e pertanto si allega la ricevuta di versamento di € 516,00

**Comment by anizzo** [comment]
Grazie per la precisazione. Spero ce ne possano essere altre di questo tipo
