### ISSUE TITLE
Moduli edilizia

### ISSUE THREAD

**Issue by dbretto** [italia/moduli-pa#32]
salve, sono stato assente assente ai più recenti incontri relativi sulla modulistica edilizia, pertanto vogliate scusare se quanto dico arriva tardi o è già stato oggetto di confrontio;
in riferimento al Modulo Unico:
- nel caso di trasmissione telematica delle istanze non è obbligatorio conoscrere la PEC del Comune destinatario;
- nel modello PdC utilizzato sono riportate delle indicazioni riferite a Legge Regionale che non dovrebbero comparire;
- richiedere che i Dati geometrici siano sempre obbligatori, ancorché si escluda la CILA, andrebbe riffertito al tipo di intervento, e di fatto risulta un onere aggiuntivo per il professionista;  
- le sezioni 18 e 19 non sono presenti nei modelli nazionali, pertanto andrebbero escluse;

considerazioni in generale:
- si dovrebbe considerare che le sezioni asteriscate sono variabili e pertanto ogni regione le gestisce in fnzione delle proprie normative, quindi in questi casi il dato imporetante è se quanto prescritto dalla  sezione si applica o meno all'intervento, mentre il contentu della sezione lo si desume dal modello;
- se i campi definiti obbligatori nel tracciato determinano che lo siano anche all'interno del modello si ripropone il problema detto sopra relativo alle sezioni variabili;
- le Regioni hanno deliberato l'adozione dei modelli adeguandone i contenuti alle normative regionali, diventa un problema se la definizione del tracciato dati condiziona l'obbligatorietà del datoi anche sul modello, in modo particolare per chi ha già implementato informaticamente i modelli;

a presto, saluti

**Comment by vintra73** [comment]
Buongiorno,
in merito alle riflessioni riportare mi preme evidenziare che:

- i dubbi sulle obbligatorietà dei dati sono di tutto il GdL, infatti nelle attività di refactoring prevista il consolidamento delle obbligatorietà è uno dei temi aperti. Mi preme ringraziare il contributo di Regione Lombardia che potete consultare all'URL https://drive.google.com/drive/folders/0BySkO0aDdHPzamVXcWMyWWZ0SlE che, tra le altre, nel folder "Specifiche Moduli Edilizi RL" ha condiviso il loro lavoro realizzato relativamente all'obbligatorietà dei dati. 

- i dubbi relativi alla possibilità di personalizzare, da parte delle Regioni, gli XML Schema per le sezioni annotate con (*) dai moduli approvati è stato implementato attraverso l'utilizzo degli abstract type previsto nelle specifiche XSD. In sintesi le Regioni provvedono ad estendere gli XML schemi prodotti implementando, conformemente alle proprie esigenze, gli abstract type.
