### ISSUE TITLE
Informazioni comuni

### ISSUE THREAD

**Issue by marmorin** [italia/moduli-pa#34]
Alcune considerazioni da sottoporre al gruppo di lavoro:
ho trovato in SUE-commons-components alcuni elementi che forse si potrebbero ritenere di interesse comune e non legati allo specifico contesto SUE
- la figura del Professionista con le relative specializzazioni (indirizzo studio,  contatti e iscrizione ad un Ordine) 
- la relazione dati Impresa e suo Legale rappresentante citata varie volte con denominazioni diverse
 -  l’Ubicazione (intesa come somma di Indirizzo più Scala, Piano, Interno ed eventuali coordinate)

**Comment by vintra73** [comment]
La ringrazio per la segnalazione, cosi come pianificato, a valle della conclusione del lavoro sugli XSD del SUE prevediamo un'azione di refactoring in cui prevedere anche il posizionamento dei type. 

Il suo suggerimento ci è di estremo aiuto e la invito a proseguire l'ispezione degli XSD per segnalarci altri type che avrebbero l'esigenza di essere spostati.

**Comment by giacomo83** [comment]
Concetto espresso anche nell'issue #38
