### ISSUE TITLE
Allegati - ipotesi di refactoring

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#35]
Alla luce di quanto emerso nell'ultimo incontro, sulla corposità degli allegati, oltre che sulla loro numerosità, in attesa di definire come potrà risolversi, a livello architetturale, la questione dello scambio di documenti, e partendo dal presupposto che allo stato attuale la pratica è costituita dagli XML contenenti i dati + gli allegati fisici (cfr. regole tecniche definite), ma che in base ai nuovi tracciati si raddoppierà la dimensione della pratica, visto che gli allegati saranno contenuti come binario anche negli XML, chiedo se sia possibile rivedere il campo: 
<xs:complexType name="FileAttachmentType">
        <xs:sequence>
            <xs:element name="contenuto" type="xs:base64Binary"/>
            <xs:element name="mimeType" type="enumeration:MimeTypeEnum"/>
        </xs:sequence>
</xs:complexType>
sostituendo il contenuto con l'hash calcolato secondo un  prefissato criterio.
A meno che non si rivedano le regole tecniche e non si scelga di eliminare gli allegati fisici, perché già inclusi negli XML.

**Comment by vintra73** [comment]
La ringrazio della segnalazione, in merito provvederemo al consolidamento di quanto da lei evidenziando provvedendo a ridefinire i type in maniera opportuna per evitare la duplicazione in caso di allegato strutturato.

**Comment by giacomo83** [comment]
fix by commit 7134ea2d29fad16e6ecce4b209fff1ab64b5febb
