### ISSUE TITLE
SUAP: anomalia in modulo subingresso

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#36]
Segnalo che nel modulo **SUAP_modulo_subingresso-1.0.0.xsd**
è presente il tag:
<xs:complexType name="DichiarazioniType">
        <xs:choice>
            <xs:element name="commercioSomministrazione" type="suapcommon:DichiarazioniType"/>
            <xs:element name="acconciatori" type="suapcommon:DichiarazioniResponsabileTecnicoAcconciatoriType" />
            <xs:element name="estetisti" type="suapcommon:DichiarazioniResponsabileTecnicoEstetistiType"/>
        </xs:choice>
</xs:complexType>
contenente riferimenti a: 
_suapcommon:DichiarazioniResponsabileTecnicoAcconciatoriType_ 
_suapcommon:DichiarazioniResponsabileTecnicoEstetistiType_ 
non presenti in **SUAP_common_components-1.0.0.xsd**

**Comment by giacomo83** [comment]
Si tratta di un piccolo refuso di cui ci eravamo accorti, il fix è già programmato nel prossimo refactoring.

Grazie comunque per la segnalazione.

**Comment by giacomo83** [comment]
Fixed on branch dev-v1.0.1 on commit d78513e97c576726ac64a5b21ae01ef713137f4b
