### ISSUE TITLE
SUE: check Regolarità Urbanistica in common components

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#37]
Nei moduli cartacei la sezione "f) Regolarità urbanistica e precedenti edilizi"  prevede la scelta alternativa di 3 campi (f.1 - pienamente conforme, f.2 in difformità, f.3 - senza titoli abilitativi).
Per i campi f.1 ed f.2 possono essere effettuate le ulteriori scelte f.(1-2).1, f.(1-2).2, ..., f.(1-2).11.
Nell'XSD, tag _<xs:group name="RegolaritaUrbanisticaOptionGroup">_, le ulteriori scelte sono associate al solo caso f.2: 
_<xs:element name="inDifformita" type="suecommon:InDifformitaType"/>_
mentre il caso f.1 risulta essere vuoto: 
_<xs:element name="pienamenteConforme" type="basic:EmptyType"/>_
E' possibile effettuare una verifica?

Segnaliamo inoltre che le voci previste nel tag:
_<xs:element name="inDifformita" type="suecommon:InDifformitaType"/>_
dovrebbero essere valide per tutti i modelli, mentre fanno riferimento solo a B1 - SCIA, invece in B2 - SCIA alternativa al PDC e PDC è presente una ulteriore voce (comunicazione di inizio dei lavori asseverata), che non trova corrispondenza nell'XSD.

**Comment by vintra73** [comment]
La ringrazio per l'osservazione, verificheremo con attenzione quanto da lei indicato

**Comment by giacomo83** [comment]
A valle di una verifica fatta anche in relazione alle issue #56 e #61 l'osservazione risulta essere valida, si provvederà al fixing in concomitanza con quello delle issue riferite.

**Comment by giacomo83** [comment]
Fix By commit 3a6e397 on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
