### ISSUE TITLE
osservazioni su Soggetti coinvolti

### ISSUE THREAD

**Issue by marmorin** [italia/moduli-pa#38]
in  TecniciIncaricatiType credo siano invertiti i tipi ProfessionistaAnagraficaType e ProfessionistaAnagraficaDirettoreType

<xs:complexType name="TecniciIncaricatiType">
        <xs:sequence>
            <xs:element name="schedaProgettistaOpereArchitettoniche" type="suecommon:ProfessionistaAnagraficaDirettoreType"  minOccurs="1"/>

           <xs:element name="schedaDirettoreOpereArchitettoniche" type="suecommon:ProfessionistaAnagraficaType" minOccurs="0"/>

            <xs:element name="schedaProgettistaOpereStrutturali" type="suecommon:ProfessionistaAnagraficaDirettoreType" minOccurs="0" />

            <xs:element name="schedaDirettoreOpereStrutturali" type="suecommon:ProfessionistaAnagraficaType" minOccurs="0" />

            <xs:element name="schedaAltriTecnici" type="suecommon:AltriTecniciType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

serve specificare professionistaAbilitato per la qualifica di Direttore? 
l'opzione è usata nella Dichiarazione di agibilità in cui il professionista si dichiara direttore o meno

 l'utilizzo delle anagrafiche nei vari moduli e usarle in maniera coerente
<xs:complexType name="ProfessionistaAnagraficaDirettoreType">
        <xs:complexContent>
            <xs:extension base="suecommon:ProfessionistaAnagraficaType">
                <xs:choice minOccurs="0">
                    <xs:element name="direttoreLavori" type="basic:EmptyType"/>
                    <xs:element name="professionistaAbilitato" type="basic:EmptyType"/>
                </xs:choice>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

come proposta di discussione credo che Soggetti coinvolti sia un concetto presente anche in SUAP e in altri tipi di istanze (nel sistema FVG gestiamo questa sezione in maniera indipendente sempre e non solo per  l'edilizia)
le entità base sono Persona fisica, Professionista o Impresa, 
poi vengono utilizzati i Ruoli con eventuali attributi specifici
alcuni sono di carattere generale, altri specifici del dominio
Generali:
Titolare/intestatario/richiedente
		Persona fisica o in qualità di …. 
			Impresa

Elenco altri titolari

Procuratore/Delegato 
		Persona fisica o Professionista

Specifici SUE:
Tecnico incaricato dei lavori 
	Professionista Direttore
	Professionista Progettista
        Professionista Altro tecnico (specificare incarico obbligatorio, abilitazione e ditta eventuali)

Impresa esecutrice dei lavori 

la dichiarazione Tecnici individuati prima dell’inizio dei lavori la vedrei in alternativa ad un Elenco tecnici dichiarati 
choice
	Elenco tecnici dichiarati:
			Opere architettoniche Direttore
                        Opere strutturali Progettista
                        Opere strutturali Direttore
			Elenco altri tecnici
				Altro tecnico
		oppure
	Flag Tecnici individuati prima dell’inizio dei lavori

Opere architettoniche Progettista  rimane obbligatorio fuori dal choice
	
anche per l'esecuzione lavori si potrebbe usare una scelta di questo tipo:
Esecuzione lavori
	Choice
		Impresa individuata prima dell’inizio dei lavori
		Impresa esecutrice
			Dati impresa (incluso legale Rappresentante)
			Dati previdenza
		In proprio

.......????   che ne pensate?......

**Comment by vintra73** [comment]
Credo che possa essere un tema da approfondire nei prossimi giorni.

La ringrazio per il suo contributo.

**Comment by giacomo83** [comment]
Segnalazione di inversione type in TecniciIncaricatiType non riscontrata.

**Comment by giacomo83** [comment]
Alla luce degli approfondimenti fatti nella call del 23/03/2018 del GdL XML si riportano le seguenti osservazioni condivise:

Allo stato attuale si è seguito un approccio di generalizzazione dove entità generiche quali Persone fisica e Impresa sono definite al più alto livello di aggregazione della gerarchia dei tipi definiti (vedi `aggregate:PersonaAnagraficaType` e `aggregate:ImpresaAnagraficaType`), si operato poi la specializzazione nello specifico contesto (nel modello di FVG  è realizzata mediante il meccanismo dei ruoli) attraverso un approccio che prevede l’implementazione di type che estendono i type delle entità generiche, posizionandoli nella gerarchia al livello circoscritto all’ambito in cui questi sono utilizzati, esemplificando se la specializzazione, come è accaduto per l’allegato **D. Soggetti coinvolti comune ai moduli del SUA CILA, SCIA e CIL** è circoscrivibile al solo dominio SUE, questa è collocata al livello `suecommon`, qualora in futuro si dovesse presentare una casistica dove type definiti ad un livello della gerarchia diventano condivisibili ad un livello più alto si procederà alle dovute attività di refactoring per indirizzare l’implementazione in tal senso.

Per quanto concerne la dichiarazione Tecnici individuati prima dell’inizio dei lavori e Impresa individuata prima dell’inizio dei lavori da riferire attraverso come alternativa, questa è già indirizzata in tal senso, motivo per cui si invitano i partecipanti del Gdl a fornire indicazioni puntuali di eventuali bug in tal senso mediante il meccanismo degli issue della piattaforma GitHub.
