### ISSUE TITLE
Segnalazioni per AgID Vocabularies

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#39]
Si segnalano i seguenti errori di scrittura per **CCIAAEnum** in _AgID_enumeration-1.0.0.xsd_:
<xs:enumeration value="PAERMO"/>
<xs:enumeration value="PAR;A"/>
<xs:enumeration value="PESARA E URBINO"/>
Inoltre <xs:enumeration value="VENEZIA ROVIGO DELTA LAGUNARE"/> andrebbe eliminato, in quanto rappresenta una nuova camera accorpata (e non è l'unica), ma nel Registro Imprese continuano ad essere mappate nella codifica REA le 105 province definite da un decreto del MiSE, alle quali corrispondono le CCIAA pre-accorpamento.

**CAP** e **REA**: rispettivamente sono definiti di lunghezza esattamente pari a 6 e 10.
In questo modo è però necessario aggiungere tanti "0" in testa al valore reale, per soddisfare la regola.
Si segnala che il REA può anche essere lungo 1.

**Comment by vintra73** [comment]
Grazie

**Comment by giacomo83** [comment]
Fixed by Commit db90b26 on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
(Pull Request #43)
