### ISSUE TITLE
SUAP/SUE: superfici in common components

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#40]
Tutte le superfici negli XSD sono espresse come _integer_.
Nella modulistica approvata non è specificato come debbano essere espresse le superfici, ma la maggior parte delle volte sono comunicate non come interi, bensì con decimali.
E' infatti necessario per taluni adempimenti (cfr. limiti imposti nella prevenzione incendi, ...) rilevare il dato in maniera più precisa.
E' opportuno definire diversamente da _integer_ questi elementi?
In caso si decida di mantenere valori interi andrà deciso come far comunicare questi dati (arrotondamento per eccesso o per difetto).

**Comment by vintra73** [comment]
Grazie, coglieremo il suggerimento di utilizzare in sostituzione gli integer con decimal

**Comment by giacomo83** [comment]
Cambiati integer con decimal  
(Pull Request #43)
Commint db90b26e28288bfd110f76fdc4123eba11730320
