### ISSUE TITLE
SUE: D. SOGGETTI COINVOLTI - 3. Imprese Esecutrici - Dati per la verifica della regolarità contributiva

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#41]
Per la sezione: 
**D. SOGGETTI COINVOLTI - 3. Imprese Esecutrici - Dati per la verifica della regolarità contributiva**
ai segnala che le 3 scelte:
_cassa edile_
_INPS_
_INAIL_ 
dovrebbero essere considerate non mutuamente esclusive (check e non radio).

**Comment by giacomo83** [comment]
Fix con scelte non  mutuamente esclusive
(Pull Request #43)
Commit db90b26 on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
