### ISSUE TITLE
SUAP: trasferimento e ampliamento

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#42]
Per i seguenti moduli:
_1.	Esercizio di vicinato 
2.	Media e grande struttura di vendita
3.	Vendita in spacci interni
7.	Bar, ristoranti e altri esercizi di somministrazione di alimenti e bevande (in zone tutelate)
8.	Bar, ristoranti e altri esercizi di somministrazione di alimenti e bevande (in zone non tutelate)_

si segnala che gli adempimenti di trasferimento e ampliamento possono essere contestuali, quindi è possibile presentare un'unica istanza SUAP che genera, quindi, un unico MDA.XML.

In questo caso i due elementi evidenziati:
            <xs:choice>
                <xs:element name="apertura" type="xxxxxx:AperturaType"/>
                **<xs:element name="trasferimento" type="xxxxxx:TrasferimentoType"/>
                <xs:element name="ampliamento" type="xxxxxx:AmpliamentoType"/>**
            </xs:choice>
NON possono essere mutualmente esclusivi, ma presenti insieme.

**Comment by ilariabrunoinfocamere** [comment]
La nota vale anche per il modulo:
_Agenzia di affari_ 
per il quale, inoltre, si segnala che l'elemento aggiuntivo _altreDichiarazioni_ rappresenta una parte dell'intervento di apertura e trasferimento, e non può essere dunque alternativo alle altre voci.

**Comment by giacomo83** [comment]
Relativamente alla prima parte del commento si rimette la discussione al GDL XML Schema.
Si segnala invece che la seconda parte della segnalazione è stata corretta in fase di refactoring (commit d572b74)

**Comment by giacomo83** [comment]
fix by commit 4d29b9d
