### ISSUE TITLE
SUE: SOGGETTI COINVOLTI - 1. TITOLARI

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#49]
Si segnala che l'elemento: 
_sueCommon.TitolareType_ 
prevede l'obbligatorietà per i campi: 
_inQualitaDi
impresa_ 
che dai modelli cartacei:
D - SOGGETTI COINVOLTI (valevole per SCIA, SCIA Alt., CIL, CILA)
PDC - SOGGETTI COINVOLTI
sono opzionali (Da compilare solo nel caso in cui il titolare sia una ditta o società)

**Comment by giacomo83** [comment]
Segnalazione recepita, si provvederà al fix nel refactoring eliminando l'Occurrence Indicator  `minOccurs="1"` negli elementi  `inQualitaDi` e `impresa` del type  `TitolareType`

**Comment by giacomo83** [comment]
Fix by commit 3a6e397  on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
