### ISSUE TITLE
SUE Agibilità: SOGGETTI COINVOLTI - 1. TITOLARI

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#50]
Si segnala che nell'xsd dell'Agibilità sono presenti sia l'elemento:
_soggettiCoinvolti_ (contenente solo _schedaTitolare_)
che l'allegato:
_TabellaAllegatiType.scpa:AllegatiSCPAType.suecommon:allegatoSoggettiCoinvolti_ (contenente, oltre a _Titolari_ anche _TecniciIncaricati_ obbligatoriamente e _ImpreseEsecutrici_)

Per l'Agibilità l'unica sezione prevista è quella dei Titolari, come giustamente mappato nell'elemento presente nell'XSD, l'aggiunta dell'allegato strutturato presuppone invece una replica dei dati dei Titolari e l'errato obbligo al popolamento dei Tecnici incaricati.

**Comment by giacomo83** [comment]
Segnalazione recepita, si provvederà al fix nel refactoring elimando il riferimento a `allegatoSoggettiCoinvolti` nel type di riferimento.

**Comment by giacomo83** [comment]
Fixed by  commit bd7e217 on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
