### ISSUE TITLE
SUE: Calcolo del contributo di costruzione

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#51]
Si segnala che gli elementi: 
_titoloGratuito
titoloOneroso_
presenti in: 
_permcostr:CalcoloContributoBaseType
scia:CalcoloContributoBaseType
scialt:CalcoloContributoBaseType_
sentito il parere del Tavolo Tecnico Regionale Veneto sulla modulistica, dovrebbero essere esclusivi.

Moduli di riferimento:
PDC --> f) Calcolo del contributo di costruzione f.1 e f.2
B1-SCIA e B2-SCIA ALT. --> g) Calcolo del contributo di costruzione (*) g.1 e g.2

**Comment by giacomo83** [comment]
La segnalazione trova riscontro positivo soltanto nelle implementazioni dei type:
- `scia:CalcoloContributoType` 
- `scialt:CalcoloContributoType `
che estendono il type astratto `suecommon:CalcoloContributoBaseType`. 

Si provvederà al fix in fase di refactoring

**Comment by giacomo83** [comment]
Fix By commit 47f28ed
