### ISSUE TITLE
SUE: Relazione Tecnica Asseverazione – Produzione di materiali di risulta

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#52]
Si segnala che gli elementi: 
_volInfUgu6000
volSup6000_
presenti in: 
_suecommon:MaterialiRisultaBaseType.comportaProduzione_
sentito il parere del Tavolo Tecnico Regionale Veneto sulla modulistica, dovrebbero essere esclusivi.

Modulistica di riferimento:
PDC, B1-SCIA, B2-SCIA ALT. -->
Relazione Tecnica Asseverazione – 8) Produzione di materiali di risulta (*) 8.2.1 e 8.2.2

**Comment by giacomo83** [comment]
Segnalazione recepita, si provvederà al fix in fase di refactoring

**Comment by giacomo83** [comment]
Fix By commit 47f28ed
