### ISSUE TITLE
SUE: Relazione Tecnica Asseverazione – Amianto

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#53]
Si segnala che gli elementi: 
_interessano
nonInteressano_
presenti in: 
_RelazioneTecnicaAsseverazioneType.AmiantoType_
dovrebbero essere invertiti, in quanto l'elemento _allegato_ è erroneamente presente sotto _nonInteressano_ al posto di _interessano_.
Modulistica di riferimento:
PDC, B1-SCIA, B2-SCIA ALT. -->
Relazione Tecnica Asseverazione – 10) Amianto 10.1 e 10.2

Si segnala, inoltre, che per il PDC nel tag:
_AmiantoType.nonInteressano_ 
va prevista la voce 10.2.2) sarà presentato 30 giorni prima dell’inizio dei lavori

**Comment by giacomo83** [comment]
Segnalazione recepita, si provvederà al fix in fase di refactoring

**Comment by giacomo83** [comment]
Fix By commit 47f28ed
