### ISSUE TITLE
SUE: Agibilità - Relazione Tecnica Asseverazione – Toponomastica 

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#54]
Si segnala che gli elementi: 
_comportaVariazioneCivici
nonComportaVariazioneCivici_
presenti in: 
_scpa:ToponomasticaType_
dovrebbero essere invertiti, infatti:
_allegaRichiestaNumerazione
protocolloVariazioneNumerazione_
dovrebbero appartenere a _comportaVariazioneCivici_

Modulistica di riferimento:
Agibilità --> Relazione Tecnica Asseverazione – 6) Toponomastica 6.1 e 6.2

**Comment by giacomo83** [comment]
Segnalazione recepita, si provvederà al fix in fase di refactoring

**Comment by giacomo83** [comment]
Fix By commit 47f28ed
