### ISSUE TITLE
SUE: Relazione Tecnica Asseverazione – Consumi energetici

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#55]
Si segnala che le seguenti 3 voci:
_ricadeSpessoriDistanze
ricadeDistanze
ricadeBonusVolumetrico_
appartenenti all'elemento:
_suecommon:ConsumiEnergeticiType_
sono giustamente alternative, ma non è necessario che ne sia presente almeno una.

In impresainungiorno.gov.it, sentito il parere del Tavolo Tecnico Regionale Veneto sulla modulistica, è stato risolto aggiungendo una 4° voce "L'intervento non ricade in alcuno dei casi sopra elencati"

Modulistica di riferimento:
B1-SCIA e B2-SCIA ALT. -->
Relazione Tecnica Asseverazione – 6) Consumi energetici (*) che l’intervento in relazione al miglioramento energetico degli edifici 6.3.1, 6.3.2, 6.3.3
PDC -->
Relazione Tecnica Asseverazione – 6) Consumi energetici (*) che l’intervento in relazione al miglioramento energetico degli edifici 6.5, 6.6, 6.7

**Comment by giacomo83** [comment]
A valle di verifiche abbiamo riscontrato che la casistica evidenziata si presenta anche su altri type, in cui esiste la possibilità di una scelta alternativa comprensiva della possibilità di nessuna selezione.

Per tali casistiche si propone, e se ne discuterà con il GdL XML Schema, di adottare in fase di refactoring una soluzione che preveda per l'Order Indicator `choice` relativo, l'utilizzo del solo Occurrence Indicator `minOccurs="0"`  sullo stesso.

**Comment by giacomo83** [comment]
Applicato il fix per la casistica specifica segnalata
