### ISSUE TITLE
SUE: Regolarità urbanistica e precedenti edilizi

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#56]
Si segnala che in: 
_suecommon:RegolaritaUrbanisticaOptionGroup_
il blocco delle informazioni presente per l'elemento: 
_inDifformita_ 
deve essere presente anche per 
_pienamenteConforme_

come indicato nella modulistica alla sezione "Regolarità urbanistica e precedenti edilizi", e) per il PDC ed f) per B1-SCIA e B2-SCIA ALT, dove l'elenco delle voci presenti fa riferimento sia a e.2.1 (f.2.1) che e.2.2 (f.2.2)

**ISSUE REPLICA DI #37**: si può chiudere uno dei 2

**Comment by giacomo83** [comment]
Si ritiene di accogliere la richiesta anche in relazione alla valutazione dell'issue #61

**Comment by giacomo83** [comment]
Fix by commit 3a6e397  on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
