### ISSUE TITLE
SUE: CIL - Impresa esecutrice dei lavori e Soggetti Coinvolti

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#57]
Si segnala per il modello C-CIL, tra i Soggetti Coinvolti è obbligatoria la sola sezione: 
f) Impresa esecutrice dei lavori.

Nell'XSD è previsto anche l'allegato: _cil:TabellaAllegatiType.cil:AllegatiCILType.suecommon:allegatoSoggettiCoinvolti_ 
che prevede invece l'obbligatorietà per _TecniciIncaricati_

**Comment by giacomo83** [comment]
La segnalazione risulta corretta, ciò che ha forviato l'implementazione è l'indicazione riguardo i Tecnici Incaricati come blocco obbligatorio sulla scheda Soggetti Coinvolti che sembra essere errata in quanto il modulo CIL non coinvolge Tecnici Incaricati.

Si provvederà ad adottare una soluzione implementativa conforme ad entrambe le casistiche rilevate.

**Comment by giacomo83** [comment]
Fixed by commit 78b882b
