### ISSUE TITLE
SUE: Relazione Tecnica Asseverazione – Barriere Architettoniche

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#60]
Si segnala che gli elementi:
_nonSoggetto
edificioPrivatoApertoAlPubblico
soggetto
soggettoNonRispetta_
presenti in
_suecommon:BarriereArchitettonicheType_
e: 
_nonSoggettoPrescrizioni
soggettoPrescrizioni
soggettoPrescrizioniEdificoPubblico_
presenti in 
_scpa:BarriereArchitettonicheType_
sentito il parere del Tavolo Tecnico Regionale Veneto sulla modulistica, dovrebbero essere non esclusivi.

Modulistica di riferimento:
PDC, B1-SCIA, B2-SCIA ALT. -->
Relazione Tecnica Asseverazione – 4) Barriere Architettoniche 4.1, 4.2, 4.3, 4.4
Agibilità -->
Relazione Tecnica Asseverazione – 4) Barriere Architettoniche 4.1, 4.2, 4.3

**Comment by vintra73** [comment]
Al fine di recepire il suggerimento si propone di cambiare l'Order Indicator choice con l'Order Indicator sequence

**Comment by giacomo83** [comment]
Fixed by commit 78b882b
