### ISSUE TITLE
SUE: Regolarità urbanistica e precedenti edilizi 2

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#61]
Si segnala che in:
_suecommon:RegolaritaUrbanisticaOptionGroup_
le informazioni presenti nel blocco per gli elementi:
_inDifformita
pienamenteConforme_
sentito il parere del Tavolo Tecnico Regionale Veneto sulla modulistica, dovrebbero essere non esclusive.

Modulistica di riferimento:
PDC -->
e) Regolarità urbanistica e precedenti edilizi e.2.(1-2).1 ... e.2.(1-2).12
B1-SCIA, B2-SCIA ALT. -->
f) Regolarità urbanistica e precedenti edilizi f.2.(1-2).1 ... f.2.(1-2).12

ISSUE CORRELATO A #56

**Comment by giacomo83** [comment]
Allo stato attuale il type è implementato con la seguente forma:

`
<xs:complexType name="InDifformitaType">
            <xs:sequence>
                <xs:element name="dataRealizzazioneOpere" type="xs:date"/>
                <xs:choice>
                    <xs:element name="titoloUnico" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="permessoLicenzaConc" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="autorizzazioneEdilizia" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="comunicazioneEdilizia" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="condonoEdilizio" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="denunciaInzioAttivita" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="DIA_SCIAAlternativa" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="certificazioneInizioAttivita" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="comunicazioneEdiliziaLibera" minOccurs="0" type="aggregate:AttoBaseType"/>
                    <xs:element name="altraPraticaEdilizia" minOccurs="0" type="suecommon:AltraPraticaEdiliziaType"/>
                    <xs:element name="primoAccatastamento" minOccurs="0" type="basic:EmptyType"/>
                </xs:choice> 
            </xs:sequence>
    </xs:complexType> `

Al fine di recepire il suggerimento si propone di cambiare l'Order Indicator choice con l'Order Indicator sequence

**Comment by giacomo83** [comment]
Fix by commit 3a6e397  on branch https://github.com/italia/moduli-pa/tree/dev-v1.0.1
