### ISSUE TITLE
moduli-pa-dev-mod-jan-18:AgID_aggregate_components-1.0.0:LuogoGroup

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#63]
la struttura del gruppo di elementi viene utilizzata nei tipi che definiscono luoghi ed indirizzi e contiene indicazione di uno stato(obbligatorio), regione, provincia, comune(obbligatorio); 
l'elemento "stato" è definito esclusivamente tramite un testo (stringa) e non si avvale di un codice identificativo riconosciuto quale il relativo codice istat che consentirebbe certa individuazione dello stato;
l'elemento "comune" risulta obbligatorio e richiede la valorizzazione obbligatoria dell'attributo codice istat che tuttavia risulta non valorizzabile in caso di luoghi/indirizzi esteri;
Si propone di inserire la codifica istata per l'elemento stato e di individuare una diversa rappresentazione per luoghi/indirizzi nazionali/esteri al fine di avere una rappresentazione completa e corretta.

**Comment by ilariabrunoinfocamere** [comment]
Salve, se può essere utile segnalo che le Regole Tecniche del DPR 160/2010, pubblicate sul portale impresainungiorno.gov.it, gestiscono la città italiana (con provincia e comune) e la città straniera (come stringa libera) a seconda del valore dello stato.
Lo stato a sua volta è identificato anche attraverso i codici ISO 3316-1, istat, catastale.
Riferimento: [Definizione delle strutture dati elementari di impresainungiorno (vers. 1.0)](http://www.impresainungiorno.gov.it/documents/155997/157492/Definizione+delle+strutture+dati+elementari+di+impresainungiorno.xsd/43929369-48f0-4b7b-883e-f57dc5cdd41e)

**Comment by giacomo83** [comment]
Si propone di valutare con il GdL XML Schema la codifica più opportune da utilizzare.

**Comment by giacomo83** [comment]
Si segnala in merito alla possibilità di rappresentazione della località estera, questa è stata risolta con la chiusura della issue #76
Per quanto concerne la possibilità di adottare una codifica standard per gli stati, rimane quanto proposto al precedente commento.

**Comment by giacomo83** [comment]
Sentito il parere del GdL XML Schema nella riunione del 23/03/2018 si opta per la scelta mono-codifica ISO ISO 3166-1 alpha-2 code

**Comment by giacomo83** [comment]
Fix by commit a74495f
