### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : AgID_enumeration-1.0.0 : NazioniAlpha3Enum

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#64]
L'enumerazione in oggetto riporta l'elenco delle cittadinanze sotto forma di stringhe di 3 caratteri. Un tale elenco risulta avere una certa variabilità e potrebbe essere preferibile una rappresentazione diversa attraverso una restriction con regular expression di validazione che consenta una maggior resilienza al cambiamento.

**Comment by vintra73** [comment]
La scelta fatta durante i lavori partiva dall'adozione dello standard ISO 3166-1 alpha-3 (https://it.wikipedia.org/wiki/ISO_3166-1_alpha-3).
