### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : AgID_enumeration-1.0.0 : TipoDocumentoSoggiornoEnum

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#65]
L'enumerazione contiene l'elenco delle tipologie di documento di soggiorno ammissibili. Tale elenco risulta avere una certa variabilità dovuta all'evoluzione normativa; potrebbe essere preferibile una rappresentazione con elemento di tipo stringa ed una restriction con regular expression di validazione che consenta una maggior resilienza al cambiamento, consentendo in futuro il cambiamento della sola regular expression di validazione.
Esempio:
<xs:simpleType name="TipoDocumentoSoggiornoEnum">
<xs:annotation>
<xs:documentation>
Elenco delle tipologie di documento di soggiorno
</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:pattern value="PERMESSO_SOGGIORNO|DOCUMENTO_IDENTITA|PASSAPORTO|DICHIRAZIONE_PRESENZA|ATTESTAZIONE_REGOLARITA_SOGGIORNO_UE|ALTRO"/>
</xs:restriction>
</xs:simpleType>

**Comment by giacomo83** [comment]
Si suggerisce un modalità di implementazione alternativa tramite enum, ma questa non è conforme con quanto condiviso dal Gdl XML Schema, in merito ai pattern implementativi definiti, nello specifico il pattern denominato  "Gestione Quesiti con voci di risposta a scelta  singola/multipla".
