### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_common_components-1.0.0 : DichiaranteType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#67]
Il tipo in oggetto si compone di un elemento denominato "inQualità" caratterizzato da una choice in cui a parte l'elemento denominato "altro" che contiene un testo, rappresentante il contenuto informativo caratterizzante la suddetta scelta, gli altri elementi sono privi di contenuto e "autodescrittivi" (titolare, legale rappresentate); 
Suggeriamo una diversa rappresentazione che riteniamo essere più resiliente al cambiamento, attraverso una choice dove oltre la scelta "altro" vi sia un elemento "tipo" di tipo stringa con opportuna restriction ai soli valori ammissibili.
Esempio:
	<xs:element name="inQualita" minOccurs="1">
		<xs:complexType> 
			<xs:choice>
				<xs:element name="tipo" type="InQualitaType" minOccurs="0"/>
				<xs:element name="altro" type="xs:string"  minOccurs="0"/>
			</xs:choice> 
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="InQualitaType">
	<xs:annotation>
	<xs:documentation>
	Elenco delle tipologie di ruolo assumibili
	</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
	<xs:pattern value="TITOLARE|LEGALE RAPPRESENTANTE"/>
	</xs:restriction>
	</xs:simpleType>

**Comment by giacomo83** [comment]
Si suggerisce un modalità di implementazione alternativa tramite enum, ma questa non è conforme con quanto condiviso dal Gdl XML Schema, in merito ai pattern implementativi definiti, nello specifico il pattern denominato  "Gestione Quesiti con voci di risposta a scelta  singola/multipla".
