### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : AgID_enumeration-1.0.0 : FormaGiuridicaEnum

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#68]
L'enumerazione contiene l'elenco delle forme giuridiche assumibili da un'impresa; 
Non so valutare se l'elenco individuato sia esaustivo, ma certamente l'evoluzione normativa potrebbe portare la necessità di rivedere tale elenco; Al fine di garantire una maggiore resilienza al cambiamento dello schema riteniamo opportuno trasformare l'enumeration in un simple type di natura testuale con restriction sui valori ammissibili; 
Per tale tipologia di dati esiste una dizionario di livello nazionale definito da ISTAT per scopi statistici che suggeriamo venga utilizzato come dizionario di riferimento consentendo l'adozione dei relativi codice e superando l'attuale indicazione sottoforma di descrizione testuale.

**Comment by fbennati** [comment]
url da cui scaricare documento con codifiche ISTAT:
https://www.istat.it/it/files/2011/01/classformegiuridiche.pdf?title=Classificazione+unit%C3%A0+legali+-+15%2Ffeb%2F2006+-+classformegiuridiche.pdf

**Comment by vintra73** [comment]
L'osservazione risulta di estremo interesse ma richiede di approfondire con attenzione le codifiche standard da utilizzare, si propone di discuterne negli incontro del GdL XML Schema

**Comment by giacomo83** [comment]
fixed by commit 548eff72b93fb1773a92e65f2dad27ec1d54fbeb
