### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : AgID_enumeration-1.0.0 : IscrizioneRegistroImpreseEnum

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#69]
L'enumerazione rappresenta lo stato di iscrizione al registro imprese e viene realizzata con una enumerazione che suggeriamo possa essere trasformata in un tipo di natira testuale con regular expression di validazione.
Esempio:
  
<xs:simpleType name="IscrizioneRegistroImpreseEnum">
    <xs:annotation>
        <xs:documentation>
            Stato di iscrizione al registro imprese
        </xs:documentation>
    </xs:annotation>        
    <xs:restriction base="xs:string">
    <xs:pattern value="ISCRITTO|NON ISCRITTO|NON NECESSARIO"/>
</xs:restriction>
</xs:simpleType>

**Comment by vintra73** [comment]
Non si ritiene necessario assorbire il suggerimento in quanto la modifica non sembra mutare le possibilità espressive e, nel contempo, non cambiano gli impatti sul mantenimento degli XML schemi.
