### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_common_components-1.0.0 : IntegrazioneAnagraficaType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#70]
Il tipo contiene un elemento "datiCastali" che consente di indicare le coordinate di un solo elemento catastale; ciò ci sembra troppo limitativo per quelle attività che vengono svolte in ambiti costituiti da più elementi catastali, che non sarebbero correttamente rappresentati.
Suggeriamo che l'elemento datiCastatli sia carattrizzato dall'attributo maxOccurs="unbounded".

**Comment by giacomo83** [comment]
Si ricorda che l'attività del GdL XML Schema riguarda la formalizzazione di quanto accettato in termini di contenuti dei moduli dai soggetti coinvolti nel processo di definizione (DFP, Regioni,Comuni).

Nello specifico rispetto all'osservazione posta, il contenuto dei moduli accettati prevede l'indicazione delle coordinate di un solo elemento catastale. Per l'elemento specifico "Dati Catastali" si ricorda  che, cosi come previsto, la sezione è personalizzabile da parte delle Regioni in funzione delle proprie normative locali.

Si coglie l'occasione per ricordare che al fine di consentire alle Regioni di operare le proprie specializzazioni,  cosi come come condiviso dal GdL XML Schema,  l'implementazione delle sezioni indicate con il simbolo * è stata realizzata attraverso l'utilizzo di type astratti, fornendo nel contempo l'implementazione conforme ai moduli nazionali come estensione del relativo type astratto. Le Regioni che debbano attuare normative locali devono definire le proprie implementazioni in estensione dei type astratti relativi.
