### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_modulo_agenzie_affari-1.0.0 : AperturaType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#71]
Il tipo che rappresenta la struttura informativa del modulo in caso di Apertura di una Agenzia di Affari risulta costituito dagli elementi "datiAttivita", "AttivitaOnline" e "Dichiarazioni"  dichiarati tutti opzionali. Ciò consente, in caso di apertura, di costruire un xml valido ma privo di qualunque dato relativo all'attività. Questa interpretazione, tenendo in considerazione la modulistica cartacea da cui ha preso spunto lo schema, ci sembra troppo rilassata rispetto al generale buonsenso.
Suggeriamo  a tal proprosito che gli elementi "datiAttivita" e "Dichiarazioni" divengano obbligatori.
L'elemento "datiAttività" è costituito da una choice i cui elementi hanno indicata la loro cardinalità (minOccurs="0" maxOccurs="1"); ci sembra più corretto esprimere la cardinalità a livello di choice piuttosto che sui relativi elementi di scelta; La mancata indicazione sul modello cartacea che la scelta rispetto alla descrizione dell'attività svolta sia limitata ad un singolo elemento, può ragionevolmente far pensare che sia possibile effettuare una scelta multipla.

**Comment by fbennati** [comment]
Nel testo ho erroneamente indicato come "datiAttivita" l'elemento che è denominato "tipoAttivita".

**Comment by giacomo83** [comment]
Si ritiene di accogliere la prima parte della segnalazione (c20d647), relativa agli elementi `tipoAttivita `e `Dichiarazioni `del sezione `Apertura`.
Relativamente alla seconda parte, allo stato non è presente su i moduli cartacei un formalismo grafico per rappresentare le possibilità di scelta multipla, sulla base di quanto stabilito nel GDL XML la soluzione da adottare in caso di incertezza è quella di adottare un maggior rilassamento dei vincoli, in quanto è sempre possibile operare una restrizione degli stessi qualora successivi approfondimenti indirizzino l'implementazione in tal senso.
