### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_modulo_agenzie_affari-1.0.0 : AperturaType : tipoAttivita

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#72]
Suggeriamo che l'elemento in oggetto venga così ridefinito:

            <xs:element name="tipoAttivita">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element name="tipoAgenzia" type="TipoAgenzieAffariEnum" />
                        <xs:element name="venditausato" type="xs:string" />
                        <xs:element name="altro" type="xs:string" />
                    </xs:choice>
                </xs:complexType>
         </xs:element>

<xs:simpleType name="TipoAgenzieAffariEnum">
<xs:annotation>
<xs:documentation>
Elenco descrizione attività svolte dalle agenzie di affari
</xs:documentation>
</xs:annotation>
<xs:restriction base="xs:string">
<xs:pattern value="organizzazione eventi|abbonamenti media|info commerciali|allestimento eventi|vendita veicoli usati|biglietti|pratiche|pubblicita|assicurazioni|trasporti"/>
</xs:restriction>
</xs:simpleType>

**Comment by ilariabrunoinfocamere** [comment]
Si segnala, inoltre, che tutte le voci del _tipoAttivita_ dovrebbero essere non mutuamente esclusive, in quanto è possibile la presenza contemporanea di più elementi.

**Comment by giacomo83** [comment]
Si suggerisce un modalità di implementazione alternativa tramite enum, ma questa non è conforme con quanto condiviso dal Gdl XML Schema, in merito ai pattern implementativi definiti, nello specifico il pattern denominato  "Gestione Quesiti con voci di risposta a scelta  singola/multipla".

In relazione al secondo commento fornito da @ilariabrunoinfocamere  si ritiene di accogliere la richiesta che consiste nel cambio dell'elemento contenitore da choice a sequence.
