### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_modulo_agenzie_affari-1.0.0 : AperturaType : AttivitaOnline

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#73]
Suggeriamo la ridefinizione dell'elemento "AttivitaOnline" come di seguito descritto:

            <xs:element name="AttivitaOnline" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                            <xs:element name="modalita" type="ModalitaOnlineEnum" 
                            <xs:element name="indirizzoweb" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:simpleType name="ModalitaOnlineEnum">
                 <xs:annotation>
                     <xs:documentation>Elenco modalità di svolgimento online</xs:documentation>
                 </xs:annotation>
                 <xs:restriction base="xs:string">
                      <xs:pattern value="esclusivamente on-line|anche on-line"/>
                 </xs:restriction>
            </xs:simpleType>

**Comment by giacomo83** [comment]
Si  suggerisce un modalità di implementazione alternativa tramite enum, ma questa non è conforme con quanto condiviso dal Gdl XML Schema, in merito ai pattern implementativi definiti, nello specifico il  pattern denominato  "Gestione Quesiti  con voci di risposta a scelta  singola/multipla".
