### ISSUE TITLE
moduli-pa-dev-mod-jan-18 : SUAP_modulo_agenzie_affari-1.0.0 : AperturaType : Dichiarazioni

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#74]
Nell'elemento "Dichiarazioni" che riteniamo debba essere obblgatorio non troviamo le dichiarazioni che dalla modulistica risultano obbligatoriamente asserite dal dichiarante.
- di essere in possesso dei requisiti di onorabilità 
- che non sussistono nei propri confronti le cause di divieto, di decadenza o di sospensione previste dalla legge (art. 67 del D.Lgs. 06/09/2011, n. 159, “Effetti delle misure di prevenzione previste dal Codice delle leggi antimafia e delle misure di prevenzione, nonché nuove disposizioni in materia di documentazione antimafia”)
e si impegna:
- a tenere permanentemente affissa nei locali dell’agenzia, in modo visibile, la tabella del tariffario delle prestazioni allegata alla presente comunicazione
- a tenere un Registro giornale degli affari

Suggeriamo che nella struttura "Dichiarazioni" venga riportato quanto dichiarato in forma esplicita; sarebbe auspicabile la costruzione di un dizionario delle dichiarazioni al fine di evitare il trasporto in forma descrittiva testuale delle stesse.

**Comment by giacomo83** [comment]
La segnalazione si riferisce ad un blocco dichiarativo che non  richiede immissione dati.

Si è condiviso con il GdL XML Schema di  non trasportare negli XML contenuti testuali invariabili dei moduli, ma di considerare gli stessi impliciti, in quanto parte del layout del modulo che è sempre ricostruibile a partire dai dati trasportati negli XML relativi mediante un opportuna trasformazione in fase di rendering.
