### ISSUE TITLE
SUE: localizzazione intervento - scala/piano/interno

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#83]
Si segnala che nei 7 moduli SUE (CILA, SCIA, SCIA alternativa al PdC, CIL, Comunicazione Fine Lavori, Agibilità, PdC) è presente la sezione dei dati "scala, piano, interno" censita in _SUE_common_components_ con l'elemento _UbicazioneImmobileType_.

Tuttavia questo elemento è utilizzato solo nei moduli:
- Comunicazione Fine Lavori
- Agibilità

mentre tutti gli altri fanno riferimento a:
_suecommon:LocalizzazioneInterventoType_
oppure a:
_suecommon:LocalizzazioneInterventoGroup_
che però non consentono la tracciatura delle informazioni indicate.

**Comment by giacomo83** [comment]
Fixed by commit d572b74
