### ISSUE TITLE
SUAP: Acconciatori ed Estetisti

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#84]
Si segnala che il modello SEGNALAZIONE CERTIFICATA DI INIZIO ATTIVITÀ PER L’ESERCIZIO DELL’ATTIVITÀ DI ACCONCIATORE E/O ESTETISTA prevede l'attività congiunta di acconciatore ed estetista, ma, mentre l'elemento: 
_attivitaGroup_
prevede l'indicazione di entrambe le scelte, l'elemento:
_DichiarazioniType_
vincola la choice tra il blocco _acconciatori_ e _estetisti_
Dovrebbe essere invece possibile inserire le informazioni per entrambe le tipologie.

**Comment by giacomo83** [comment]
Fix by commit 717def0
