### ISSUE TITLE
SUAP: Attestazione imposto di bollo

### ISSUE THREAD

**Issue by ilariabrunoinfocamere** [italia/moduli-pa#86]
Nella modulistica che prevede il pagamento del bollo (ad es. modello 7. DOMANDA DI AUTORIZZAZIONE PER BAR, RISTORANTI E ALTRI ESERCIZI DI SOMMINISTRAZIONE DI ALIMENTI E BEVANDE (IN ZONE TUTELATE)) nella sezione:
_ALTRI ALLEGATI  (attestazioni relative al versamento di oneri, diritti, ecc, e dell’imposta di bollo)_
è presente l'allegato obbligatorio:
- Attestazione del versamento dell’imposta di bollo: estremi del codice identificativo della marca da bollo, che deve essere annullata e conservata dall’interessato;
ovvero 
- Assolvimento dell’imposta di bollo con le altre modalità previste, anche in modalità virtuale o tramite @bollo

Si descrive quale approccio è stato seguito nella piattaforma impresainungiorno:
è presente una dichiarazione come form compilabile, che produce un set di dati strutturati, senza che l'utente debba quindi allegare un documento.
Tale dichiarazione prevede la selezione obbligatoria di una delle 4 possibili opzioni:
1. **Il pagamento è dovuto e si intende assolvere l’obbligo tramite il circuito digitale pagoPA [NB: questa opzione è possibile solo se lo Sportello Unico aderisce a pagoPA]** ... (indicando se si assolve il bollo per la sola domanda o anche per l'autorizzazione, ed in questo secondo caso è necessario indicare la motivazione)
2. **Il pagamento è dovuto e si intende assolvere l’obbligo con marche da bollo di cui si riportano i numeri di serie identificativi (le marche da bollo utilizzate saranno poi annullate e conservate in originale)** ... (con l'indicazione del numero seriale della marca e data per la domanda e per l'autorizzazione, o motivazione in caso quest'ultima non sia dovuta)
3. **Per gli Enti autorizzati, l'imposta di bollo è assolta in modo virtuale ai sensi del D.M. 10/11/2011 o ai sensi dell'art. 15 D.P.R. 642/1972** ... (con allegazione obbligatoria della dichiarazione relativa all'assolvimento dell'imposta di bollo)
4. **Il pagamento non è dovuto poiché esentati** ... (con indicazione obbligatoria della motivazione) 

Nei casi 1, 2 e 4 non è richiesta alcuna attestazione all'utente, dal momento che sono indicati gli estremi previsti proprio nella sezione ALTRI ALLEGATI .

**Comment by giacomo83** [comment]
Sentito il GdL XML Schema nella riunione 22/03/2018 si convieneche è comunque necessario generare una allegato non strutturato e riferirlo all'interno del modulo cosi come previsto dalla relativa sezione "tabella degli allegati". 
Si rimette invece la discussione sulle modalità previste e indicate da Infocamere tra la stessa e le regioni, essendo una pure questione di front-end.
