### ISSUE TITLE
Problemi con l'utilizzo dei pathname relativi

### ISSUE THREAD

**Issue by deligios** [italia/moduli-pa#87]
Negli schemi pubblicati viene fatto uso di pathname relativi negli statement di import.
Questo crea problemi nell'uso di xslt 1.0 e costringe a modificare i files per utilizzarli.
Come si può ovviare al problema?

**Comment by giacomo83** [comment]
Grazie, verificheremo la problematica e valuteremo eventuali possibili soluzioni.

**Comment by giacomo83** [comment]
Abbiamo effettuato delle verifiche applicando una trasformazione XSLT ad un istanza campione di un modulo e non riscontriamo nessun problema.
Potrebbe fornirci un esempio dettagliato della casistica da lei riscontrata.
Grazie

**Comment by giacomo83** [comment]
Da un riscontro effettuato con il GdL XML Schema la problematica segnalata non è stata riscontrata da nessuno dei partecipanti.
Nel caso tale problematica risulta ancora presente, invitiamo a fornire un esempio dettagliato che ci consenta di riprodurre lo scenario dove la stessa si verifica.

**Comment by giacomo83** [comment]
Non avendo ricevuto ulteriori osservazioni in merito, il GdL ha valutato la chiusura della presente.
