### ISSUE TITLE
Uso non uniforme di xs e xsd nei namespaces

### ISSUE THREAD

**Issue by deligios** [italia/moduli-pa#89]
Nei file XSD viene fatto indifferentemente uso dei prefissi xs: e xsd: 
Questo genera problemi nel trattamento automatico degli schemi e in ogni caso sarebbe da evitare

**Comment by giacomo83** [comment]
Sarebbe possibile fornire maggiori informazioni circa il  problema riscontrato, in modo da poterci consentire le necessarie verifiche.
Grazie

**Comment by deligios** [comment]
in:

- CCTS_CCT_SchemaModule-2.1.xsd
- CoreVocabularies-AggregateComponents-1.1.xsd
- CoreVocabularies-BasicComponents-1.1.xsd
- UBL-UnqualifiedDataTypes-2.1.xsd

viene usato xmlns:xsd="http://www.w3.org/2001/XMLSchema"

in tutti gli altri schemi
viene usato xmlns:xs="http://www.w3.org/2001/XMLSchema"

A seguito degli include ci sono quindi due prefissi di namespace che puntano al medesimo schema

**Comment by giacomo83** [comment]
Non ci risulta che tale circostanza determini "problemi nel trattamento automatico".
La differenza da lei riscontrata deriva dall'adozione di schema dati a livello europeo (Core Vocabularies definiti nell'ambito del progetto ISA-square) che utilizzano xsd, mentre per le definizioni realizzate per il progetto abbiamo utilizzato il prefisso xs.

Grazie
