### ISSUE TITLE
Unità amministrative

### ISSUE THREAD

**Issue by deligios** [italia/moduli-pa#90]
Sarebbe opportuno inserire le unità amministrative come enumerazioni (almeno Regioni e Province)
Anche la dipendenza tra Unità amministrativa e relativo codice ISTAT andrebbe descritta come attributo delle entità invece che come pattern

**Comment by giacomo83** [comment]
Valuteremo il suo suggerimento con il GdL XML Schema.
Grazie

**Comment by deligios** [comment]
Lo stesso discorso vale per languageID e languageLocaleID

**Comment by deligios** [comment]
Si può riaprire sino alla valutazione del GDL?

**Comment by giacomo83** [comment]
languageID  e languageLocaleID  sono entrambi utilizzati negli schemi dati relativi ai Core Vocabularies definiti nell'ambito del progetto ISA-square.

**Comment by deligios** [comment]
OK, ma visto che per le regioni e province italiane dovrebbero essere delle costanti potremmo considerare dei default

**Comment by giacomo83** [comment]
Nello specifico degli attributi da lei indicati, questi stessi risultano opzionali, e in quanto tali non impattano su implementazioni che non considerano il multilingua.
Inoltre ci sembra poco significativo fissare un valore di default per un elemento opzionale.

**Comment by giacomo83** [comment]
Sentito il parere del GdL XML Schema rispetto all'ipotesi di adottare elenchi enumerati per le Unità Amministrative non si è reputato al momento utile adottare una tale soluzione.

Il GdL si riserva di rivalutare l'ipotesi prospettata sulla base di esempi concreti che dimostrino il reale apporto di valore di una tale soluzione, pertanto si invita @deligios  se ancora di suo interesse a fornire degli esempi in tal senso.

**Comment by giacomo83** [comment]
Non avendo ricevuto ulteriori osservazioni in merito, il GdL ha valutato la chiusura della presente.
