### ISSUE TITLE
Omogeneizzare i valori delle enum in AgID_enumeration

### ISSUE THREAD

**Issue by deligios** [italia/moduli-pa#91]
Le convenzioni adottate nei value delle enumerazioni dovrebbero essere omogeneizzate:

- Tutti i values dovrebbero essere lowercase (o uppercase)
- Nei values dovrebbero essere adottati alternativamente gli underscore o gli spazi in modo omogeneo
- Potrebbe essere riconsiderato l'uso dell'apice all'interno dei values?
- Dove vengono citate normative regionali specificare la regione (ENTE DI CUI ALLA L.R. 21-12-93, N.88)

**Comment by giacomo83** [comment]
Sono in atto attività  per normalizzare e adottare standard riconosciuti a livello nazionale/internazionale da parte del GdL XML Schema, in tali attività saranno presi in considerazione i sui suggerimenti.
Grazie

**Comment by deligios** [comment]
Sarebbe preferibile lasciare gli issues aperti sino a quando il GDL si è espresso (positivamente o negativamente)

**Comment by giacomo83** [comment]
Sentito il parere del GdL si procederà ad adottare una maggiore uniformità per le regole di naming degli enumeration.
