### ISSUE TITLE
moduli_common_components - versione 1.1.0 - AllegatoType

### ISSUE THREAD

**Issue by fbennati** [italia/moduli-pa#98]
Il tipo consente indistintamente di scegliere se inviare il contenuto binario dell'allegato all'interno del messaggio o viceversa un riferimento all'allegato.
La gestione di contenuti binari inseriti nei messaggi  in base64 è poco efficiente perchè aumenta la dimensione dei messaggi in maniera consistente rendendo più complessa la relativa elaborazione.
La trasformazione in base64 di file di dimensioni importanti è poo efficiente in termini computazionali e di dimensione (aumento medio della dimensione del 25%)
Dato che gli xml prodotti saranno certamente trasmessi tra i soggetti via PEC o in cooperazione applicativa valuterei l'ipotesi che gli allegati siano esterni al messaggio e quindi siano esclusivamente referenziati.
Il riferimento potrebbe essere arrichito dell'hash del file  (SHA-*) per potere effettuare una verifica di congruità tra il messaggio, l'allegato e per verificarne la non altreazione in sede di trasporto.

**Comment by giacomo83** [comment]
fix by commit 7134ea2d29fad16e6ecce4b209fff1ab64b5febb
